### ISSUE TITLE
bitfossil showing only partial data

### ISSUE THREAD

**Issue by xloem** [HugPuddle/Apertus#22]
I see on, for example, http://bitfossil.com/893406775fa26e873e7cfb5b8f873e8d4a22cfef07cd3158b492a87f39e8222e/index.htm , that a lot of data is stored ( http://bitfossil.com/893406775fa26e873e7cfb5b8f873e8d4a22cfef07cd3158b492a87f39e8222e/ADD ).  However, bitfossil only shows a small text message for the whole set of data

**Comment by xloem** [comment]
I think this is because it is a faulty transaction

**Comment by embiimob** [comment]
bitfossil indexes the base transactions as well as the transaction tree.  So archives with small message may show up twice.  once due to the base transactions.. and a second time after the full transaction tree has been archived.      

I believe this is the root id for the entire transaction tree.
ec45f6ef86fe3a0629efac9f08914824544ccbdbaf75a8b975c898cbd138e687
